name: 'Github Visibility'
author: '@justinbird'
description: 'A GitHub action that allows you to set the visibility of the repo to either private or public.'
inputs:
  visibility:
    description: 'Either "public" or "private" depending on if you want to make the repository public or private respectively.'
    required: true
on:
  workflow_dispatch:

runs:
  using: "composite"
  steps:
    - name: Github API
      run: >
        curl -L -X PATCH
        --fail-with-body
        -H "Accept: application/vnd.github+json"
        -H "Authorization: Bearer ${{ secrets.PRIVACY_TOKEN }}"
        -H "X-GitHub-Api-Version: 2022-11-28"
        https://api.github.com/repos/${{ github.repository }}
        -d '{"visibility":"${{ inputs.visibility }}"}'
