name: privacy

on:
  workflow_dispatch:

jobs:
  privacy:
    runs-on: ubuntu-latest

    steps:
      - name: Github API
        run: >
          curl -L -X PATCH
          --fail-with-body
          -H "Accept: application/vnd.github+json"
          -H "Authorization: Bearer ${{ secrets.PRIVACY_TOKEN }}"
          -H "X-GitHub-Api-Version: 2022-11-28"
          https://api.github.com/repos/${{ github.repository }}
          -d '{"private":"true"}'
