name: Public Test
description: A test that the action makes the repo public

on:
  workflow_dispatch:

jobs:
  run-my-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make the repo public
        uses: justinbird/github-visibility-action@main
        with:
          token: '${{ secrets.PRIVACY_TOKEN }}'
          visibility: 'public'