name: Test to make the repo public

on:
  workflow_dispatch:

jobs:
  run-my-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make the repo public
        uses: ./action.yaml
        with:
          visibility: 'public'